version: '3.8'
services:
  db:
    image: mariadb:10.6
    container_name: eyalamit-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: eyalamit_db
      MYSQL_USER: eyalamit_user
      MYSQL_PASSWORD: user_password
    volumes:
      - ./db_data:/var/lib/mysql
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: eyalamit-wp
    restart: always
    ports:
      - "9090:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: eyalamit_user
      WORDPRESS_DB_PASSWORD: user_password
      WORDPRESS_DB_NAME: eyalamit_db
    volumes:
      - .:/var/www/html
      - ./wp-content:/var/www/html/wp-content
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: eyalamit-pma
    restart: always
    depends_on:
      - db
    ports:
      - "9091:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
networks:
  default:
    name: eyalamit-network

volumes:
  db_data:



