version: '3.8'
services:
  db:
    image: mariadb:10.6
    container_name: eyalamit-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: eyalamit_db
      MYSQL_USER: eyalamit_user
      MYSQL_PASSWORD: user_password
    volumes:
      - ./db_data:/var/lib/mysql
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: eyalamit-wp
    restart: always
    ports:
      - "9090:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: eyalamit_user
      WORDPRESS_DB_PASSWORD: user_password
      WORDPRESS_DB_NAME: eyalamit_db
    volumes:
      - .:/var/www/html
      - ./wp-content:/var/www/html/wp-content
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: eyalamit-pma
    restart: always
    depends_on:
      - db
    ports:
      - "9091:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
  selenium-hub:
    image: selenium/hub:4.15.0
    container_name: eyalamit-selenium-hub
    restart: always
    ports:
      - "4444:4444"
      - "4445:4444"
    networks:
      - default
  firefox-node:
    image: selenium/node-firefox:4.15.0
    container_name: eyalamit-firefox-node
    restart: always
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NODE_MAX_INSTANCES=1
      - NODE_MAX_SESSION=1
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - default
networks:
  default:
    name: eyalamit-network

volumes:
  db_data:



